
require("./animations.module.css");
const styles = {
  cardFadeIn: 'cardFadeIn_ccce5766',
  cardSlideInLeft: 'cardSlideInLeft_ccce5766',
  cardSlideInRight: 'cardSlideInRight_ccce5766',
  cardSlideInUp: 'cardSlideInUp_ccce5766',
  cardSlideInDown: 'cardSlideInDown_ccce5766',
  cardScaleIn: 'cardScaleIn_ccce5766',
  cardRotateIn: 'cardRotateIn_ccce5766',
  cardFadeOut: 'cardFadeOut_ccce5766',
  cardSlideOutLeft: 'cardSlideOutLeft_ccce5766',
  cardSlideOutRight: 'cardSlideOutRight_ccce5766',
  cardScaleOut: 'cardScaleOut_ccce5766',
  contentExpand: 'contentExpand_ccce5766',
  contentCollapse: 'contentCollapse_ccce5766',
  contentSlideExpand: 'contentSlideExpand_ccce5766',
  contentSlideCollapse: 'contentSlideCollapse_ccce5766',
  accordionExpand: 'accordionExpand_ccce5766',
  accordionCollapse: 'accordionCollapse_ccce5766',
  cardMaximize: 'cardMaximize_ccce5766',
  cardRestore: 'cardRestore_ccce5766',
  maximizeBackdropFadeIn: 'maximizeBackdropFadeIn_ccce5766',
  maximizeBackdropFadeOut: 'maximizeBackdropFadeOut_ccce5766',
  maximizedContentSlideIn: 'maximizedContentSlideIn_ccce5766',
  maximizedContentSlideOut: 'maximizedContentSlideOut_ccce5766',
  shimmer: 'shimmer_ccce5766',
  shimmerWave: 'shimmerWave_ccce5766',
  loadingBar: 'loadingBar_ccce5766',
  spin: 'spin_ccce5766',
  pulse: 'pulse_ccce5766',
  loadingDots: 'loadingDots_ccce5766',
  progressIndeterminate: 'progressIndeterminate_ccce5766',
  cardHighlight: 'cardHighlight_ccce5766',
  cardGlow: 'cardGlow_ccce5766',
  buttonHover: 'buttonHover_ccce5766',
  iconRotate: 'iconRotate_ccce5766',
  subtleBounce: 'subtleBounce_ccce5766',
  staggeredFadeIn: 'staggeredFadeIn_ccce5766',
  cardFadeInHW: 'cardFadeInHW_ccce5766',
  cardSlideInLeftHW: 'cardSlideInLeftHW_ccce5766',
  cardSuccessHighlight: 'cardSuccessHighlight_ccce5766',
  cardErrorHighlight: 'cardErrorHighlight_ccce5766',
  errorShake: 'errorShake_ccce5766',
  cardWarningHighlight: 'cardWarningHighlight_ccce5766',
  warningPulse: 'warningPulse_ccce5766',
  cardInfoHighlight: 'cardInfoHighlight_ccce5766',
  cardComplexEntrance: 'cardComplexEntrance_ccce5766',
  cardFlip: 'cardFlip_ccce5766',
  typewriter: 'typewriter_ccce5766',
  advancedSpin: 'advancedSpin_ccce5766'
};

export default styles;
