// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

interface CssExports {
  'formContainer': string;
  'formSection': string;
  'sectionHeader': string;
}
const cssExports: CssExports = {} as CssExports;
export default cssExports;
